version: '3.8'

services:
  hotel_management-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_management
    ports:
      - "5433:5432"

  dashboard_service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dashboard_service
    ports:
      - "5434:5432"

  hotel_management:
    build:
      context: ./data_provider
      dockerfile: Dockerfile
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - hotel_management-db

  dashboard_service:
    build:
      context: ./dashboard_service
      dockerfile: Dockerfile
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    depends_on:
      - dashboard_service-db
