"""Remove room_reservation_id from events

Revision ID: f364fd6ccfbc
Revises: fb4ef7b1c673
Create Date: 2025-02-08 13:22:25.442903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f364fd6ccfbc'
down_revision: Union[str, None] = 'fb4ef7b1c673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'room_reservation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('room_reservation_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
